// 1. OPERATORS ARE FUNCTIONS 
// 2. OPERATOR PRECEDENCE --> WHICH OPERATOR FUNCTION CALLS FIRST
// 3. OPERATOR ASSOCIATIVITY -->WHAT ORDER OPERATOR FUNCTIONS GET CALLED IN" LEFT-TO-RIGHT OR RIGHT-TO-LEFT (WHEN FUNCTION HAVE THE SAME
// PRECENDENCE; THE ONE WITH THE HIGHER PRECEDENCE CALLED FIRST)

console.log(4*3/2);